<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Stock History Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header .period {
            color: #666;
            font-size: 14px;
        }
        .summary {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #2c5aa0;
            color: white;
            padding: 8px;
            text-align: left;
            border: 1px solid #ddd;
        }
        td {
            padding: 8px;
            border: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 10px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .section-title {
            background-color: #495057;
            color: white;
            padding: 8px;
            margin: 15px 0 10px 0;
            font-weight: bold;
        }
        .negative {
            color: #dc3545;
            font-weight: bold;
        }
        .positive {
            color: #28a745;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Stock History Report</h1>
        <div class="period">
            Period: {{ $start_date->format('F j, Y') }} to {{ $end_date->format('F j, Y') }}
        </div>
        <div>Generated on: {{ $generated_at->format('F j, Y g:i A') }}</div>
    </div>

    <!-- Summary Section -->
    <div class="summary">
        <strong>Report Summary:</strong><br>
        • Period: {{ $start_date->format('M j, Y') }} to {{ $end_date->format('M j, Y') }}<br>
        • Total Movements: {{ $total_movements }}<br>
        • Report Date: {{ $generated_at->format('M j, Y g:i A') }}
    </div>

    <!-- Stock History Table -->
    <div class="section-title">Stock Movement Details</div>
    <table>
        <thead>
            <tr>
                <th>Date & Time</th>
                <th>Ingredient</th>
                <th>Type</th>
                <th>Previous Stock</th>
                <th>New Stock</th>
                <th>Change Amount</th>
                <th>Reason</th>
                <th>User</th>
                <th>Order ID</th>
            </tr>
        </thead>
        <tbody>
            @foreach($stock_history as $history)
            <tr>
                <td>{{ $history['date'] }}</td>
                <td><strong>{{ $history['ingredient']->name }}</strong> ({{ $history['ingredient']->unit }})</td>
                <td>{{ $history['change_type'] }}</td>
                <td>{{ number_format($history['movement']->previous_stock, 2) }}</td>
                <td>{{ number_format($history['movement']->new_stock, 2) }}</td>
                <td class="{{ $history['movement']->change_amount < 0 ? 'negative' : 'positive' }}">
                    {{ $history['movement']->change_amount > 0 ? '+' : '' }}{{ number_format($history['movement']->change_amount, 2) }}
                </td>
                <td>{{ $history['movement']->reason ?? 'N/A' }}</td>
                <td>{{ $history['user'] }}</td>
                <td>
                    @if($history['movement']->order_id)
                        #{{ $history['movement']->order_id }}
                    @else
                        N/A
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    @if(count($stock_history) === 0)
    <div style="text-align: center; padding: 20px; color: #666;">
        No stock movements found for the selected period.
    </div>
    @endif

    <div class="footer">
        Report generated by CupsStreet POS System | Page 1 of 1
    </div>
</body>
</html>